### ISSUE TITLE
マージンブロックの表示を改善する

### ISSUE THREAD

**Issue by erukiti** [erukiti/vivliostyle-techbook-starter#14]
Re:VIEWと同じにしたい

**Comment by erukiti** [comment]
```css
  --vs-theme--page-top-right-content: '第' counter(vs-counter-chapter) '章' env(doc-title) ' ';
```

これで、章タイトルに番号を付与することはできる

が、どうも節の番号とタイトルが取得できないっぽい

```css
  --vs-theme--page-top-right-content: counter(vs-counter-chapter) '.' counter(vs-counter-sec-h2);
```

> 2.0

**Comment by erukiti** [comment]
本のタイトルをいちいち表示する必要ないやろ

**Comment by erukiti** [comment]
Re:VIEWのような、border-bottom出せないか試してみた

```css
@page {
  @top-left-corner {
    border-bottom: 1px solid #ccc;
  }
  @top-right-corner {
    border-bottom: 1px solid #ccc;
  }
  @top-center {
    border-bottom: 1px solid #ccc;
  }
}
```

なんかうまくいかない
